name: hayami_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.5.3
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0
  dropdown_search: ^6.0.2
  flutter_multi_formatter: ^2.4.0
  pdf: ^3.10.4
  printing: ^5.12.0
  sqflite: ^2.3.0
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.2
  sqflite_common_ffi_web: ^0.4.5+4
  path_provider: ^2.1.2       
  http: ^1.2.1                  
  connectivity_plus: ^6.0.3
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  http: ^1.3.0
  flutter_launcher_icons: ^0.14.4  # <-- Tambahkan ini

flutter:
  uses-material-design: true

  assets:
    #- images/kledo.png
    - assets/image/hayamibaru.png
    - assets/image/hayamilogo.png
    - assets/mydb.db


flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/hayamibaru.png"
